matrix:
  include:
    - language: ruby
      script: "bundle exec jekyll build"
    - language: node_js
      sudo: false
      dist: trusty
      language: node_js
      
      node_js:
       - "8"
      
      addons:
        chrome: stable
      
      after_success:
       - npm install -g codecov@2.x
       - codecov
      
# notifications: 
#   irc:
#     channels:
#       - "chat.freenode.net#example"